[package]
name = "sql-query-metadata"
version = "0.0.0"
edition = "2024"

[dependencies]
clap = { version = "4.5.59", features = ["derive"] }
postgres = "0.19.12"
serde = { version = "1.0.228", features = ["derive"] }
serde_json = "1.0.149"

[workspace]
