[package]
name = "sql_protocol"
version.workspace = true
rust-version.workspace = true
edition.workspace = true
license-file.workspace = true

[dependencies]
rmp = { workspace = true }
rmp-serde.workspace = true
thiserror = { workspace = true }

