[package]
name = "sql_protocol"
version.workspace = true
rust-version.workspace = true
edition.workspace = true
license-file.workspace = true

[dependencies]
comfy-table = { workspace = true }
rmp = { workspace = true }
thiserror = { workspace = true }

